### ISSUE TITLE
Detailed API documentation is missing

### ISSUE THREAD

**Issue by Sumit-Chakole** [deadpixelsociety/passport#3]
Detailed API documentation is missing

**Comment by deadpixelsociety** [comment]
What kind of details are you looking for? What would be useful? Documentation is a weakness of mine, so any tips to improve would be appreciated.

**Comment by Sumit-Chakole** [comment]
To start with, you may answer specific doubts that I am facing to integrate this lib-
1. email(), length() are few default validations available, which other validations are available? How to provide regex?

2. How to validate Spinners?

3. How to validate if confirm password matched with password field?

4. Which all Inbuilt ValidatorFactories are available like TextInputLayoutValidator

5. Can validation be triggered on change of value in textbox than on click of button?

**Comment by deadpixelsociety** [comment]
Happy to help! To preface this I wanted passport to be as non-intrusive to the user as possible and I seek to accomplish that by not requiring certain interactions beyond assigning rules and at some point calling for validation on those rules. I aim to leave implementation of specific rules and validation invocation to the developer.

1. The default available functions are available [here](https://github.com/deadpixelsociety/passport/blob/master/core/src/main/kotlin/com/thedeadpixelsociety/passport/Functions.kt). I can certainly document these specifically. Regex is available through the 'matches' function. You may pass in either your own Regex instance or a string pattern. 'doesNotMatch' is the inverse of this.
2. Spinner validation would need to be implemented as a custom validator if that's a use case you require. You can see the SwitchCompat example [here](https://github.com/deadpixelsociety/passport/blob/master/example/src/main/kotlin/com/thedeadpixelsociety/passport/example/SwitchCompatValidator.kt). 
3. This would be a custom rule where you check the text value of one view versus the other. 
````
rules<String>(confirmPasswordView) {
	rule({ it == passwordView?.text?.toString() }, { "Passwords must match. "})
}
````
4. The only core validator included is for TextView (and thus all descendants). The design library contains the TextInputLayoutValidator that you mention, and you can pull the SwitchCompat example out for use if desired. 
5. Sure. An easy way to implement this would be to trigger validation on that specific view using a [TextWatcher](https://developer.android.com/reference/android/text/TextWatcher) or something like [RxAndroid](https://github.com/ReactiveX/RxAndroid).

These items fall outside of what I would want to include in the core library, but I'm open to writing full examples for these kinds of cases or looking at creating a 'commons' type of library that includes items like these.

**Comment by Sumit-Chakole** [comment]
Thanks! I am using the lib successfully now :) Point 5 I feel should be available, I will see if I could build it and give your PR
