### ISSUE TITLE
Fields Matching validation / Confirm Password functionality

### ISSUE THREAD

**Issue by PieterPicup** [deadpixelsociety/passport#7]
Hi there. 

I was wondering if there is a validator which can compare 2 fields to each other and validate if the data is the same? Like a password and confirm password validator.

If there is please direct me to it. If not can I create a custom validator to do what I need or could the feature be added in?

Thanks

**Comment by deadpixelsociety** [comment]
Hello.

There is no built-in validator that does this. But you can create a custom validator and implement that logic easily. See the [SwitchCompat ](https://github.com/deadpixelsociety/passport/blob/master/example/src/main/kotlin/com/thedeadpixelsociety/passport/example/SwitchCompatValidator.kt) example to get you started.

**Comment by PieterPicup** [comment]
Hi

Thanks for the reply. I did manage to come right with the custom validator to impliment what I needed.
Great Lib!
